### ISSUE TITLE
Execution Issue

### ISSUE THREAD

**Issue by ghost** [Vaibhav/Stock-Analysis#1]
Good day Sir,

May I ask how one approaches the execution of this program? Although I can figure it out from the code, documentation regarding execution in README.md would be greatly appreciated.

Thanks in advance,

James Gallagher

**Comment by Vaibhav** [comment]
I will add it to the README soon, in the middle of midterm season currently. The code is modular as in, each folder has some file to run. I still have to work on encapsulating all the modules and make one big application. 

Need to figure out if I want to do it as a website or a desktop application.

**Comment by James-Gallagher** [comment]
Hello,

Thanks for your swift and helpful response. Could you please tell me what I would do for execution in the interim?

Thanks in advance,

James Gallagher

**Comment by Vaibhav** [comment]
You can use the command line and go into the directory with the file you want to run, then: 
`python <filename>.py`

**Comment by Vaibhav** [comment]
Updated repo.
