### ISSUE TITLE
where is the key_stats.csv?

### ISSUE THREAD

**Issue by heisenbergwong** [Vaibhav/Stock-Analysis#4]
hi, thanks for your great job, very grateful, but I wonder where the key_stats.csv file goes?

**Comment by Vaibhav** [comment]
Sorry, which file are you trying to run?

**Comment by heisenbergwong** [comment]
hello Vaibhav, thanks for your response, the file I want to run is Regression/linear-svc-machine-learning.py

**Comment by heisenbergwong** [comment]
I saw your code, the key_stats.csv may contains many factors like PE,PB,PEG and so on

**Comment by Vaibhav** [comment]
I actually had the path set to my backup hard drive as the key_stats.csv file I had was very large. If you open up the file, just change the path variable to wherever you have the file saved. 

You can download it from here: https://github.com/sbsar6/python-data-mining/blob/master/key_stats.csv

~Merry Christmas & Happy Holidays ~

**Comment by heisenbergwong** [comment]
Thank you so much for your great help, and also thanks for your selfless dedication about the code, the data file like a Christmas gift. This is a blessing from a Chinese friend: Merry Christmas and happy new year

**Comment by Vaibhav** [comment]
LOL, thank you for your kind words! Happy new year!
