### ISSUE TITLE
Find replacement for yahoo-finance module

### ISSUE THREAD

**Issue by jackmoody11** [Vaibhav/Stock-Analysis#9]
Will need to find a new data source for statistics. May use [IEX API](https://iextrading.com/developer/docs/) as used on my [current project](https://github.com/jackmoody11/stockScores) if a good fit.

**Comment by Prajwal-B-Ainapur** [comment]
We could also use quandl module for it has got more features!

**Comment by jackmoody11** [comment]
Quandl module is a possibility. Might need to add that API key will be useful if making lots of calls per day (I think the limit is 50/day without API key?).

**Comment by Vaibhav** [comment]
Switched to IEX for the newer scripts and deprecated the useless scripts (old + better packages out there now).
